## Network Biology 
### Coding Assignment 3
#### Submitted By: Divyanshu Srivastava

In [1]:
import networkx as nx
import numpy as np
import matplotlib as plt
import random
import copy
from Bio.PDB import *

#### Question 1


In [196]:
## Initialization

genes = 25
tfbs_pool = 10
tfbs_per_gene = 3

gene_pool = {}
for g in range(genes):
    gene_pool[g] = random.sample(range(tfbs_pool), tfbs_per_gene)

steps_of_evolution = 100

p_gene_dublication = 0.25
p_gene_deletion = 0.25
p_tfbs_dublication = 0.25
p_tfbs_deletion = 0.25
p_vector = [p_gene_dublication, p_gene_deletion, p_tfbs_dublication, p_tfbs_deletion]



## Evolution
for s in range(steps_of_evolution):
    r = np.random.choice(len(p_vector), p = p_vector)
#     print gene_pool
    if r == 0:
#         print "Evolution Step : " + str (s) + " Gene Dublication"
        gene_to_dublicate = random.sample(range(genes), 1)[0]
        gene_pool[genes] = copy.deepcopy(gene_pool[gene_to_dublicate])
        genes = genes + 1;
    elif r == 1:
#         print "Evolution Step : " + str (s) + " Gene Deletion"
        gene_to_delete = random.sample(range(genes), 1)[0]
#         gene_pool.pop(gene_to_delete)
        for i in range(gene_to_delete, genes-1):
            gene_pool[i] = copy.deepcopy(gene_pool[i+1])
#         if not gene_to_delete == genes - 1:
        gene_pool.pop(genes - 1)
        genes = genes-1
        if genes == 0:
            print "Gene Pool Empty !"
            break
    elif r == 2:
#         print "Evolution Step : " + str (s) + " TFBS Dublication"
        tfbs_probability = np.array(range(0, tfbs_pool))
        for g in gene_pool:
            for value in gene_pool[g]:
                tfbs_probability[value] = tfbs_probability[value]+1
        tfbs_probability = tfbs_probability.astype(np.float)
        tfbs_probability = tfbs_probability / np.sum(tfbs_probability)
        tfbs_to_dublicate = np.random.choice(tfbs_pool, p = tfbs_probability)
        flag = False
        while not flag:
            gene_target = np.random.choice(gene_pool.keys())
            if tfbs_to_dublicate not in gene_pool[gene_target]:
                gene_pool[gene_target].append(tfbs_to_dublicate)
                flag = True
    else:
#         print "Evolution Step : " + str (s) + " TFBS Deletion"
        gene_target = np.random.choice(gene_pool.keys())
#         print "gene_target = " + str(gene_target)
        tfbs_to_delete = np.random.choice(gene_pool[gene_target])
#         print "tfbs_to_delete = " + str(tfbs_to_delete)
        gene_pool[gene_target].remove(tfbs_to_delete)
#         print "gene pool agter deletion"
#         print gene_pool
        if len(gene_pool[gene_target]) == 0:
            
            gene_to_delete = gene_target
#             print "removing gene " + str(gene_to_delete)
#             gene_pool.pop(gene_to_delete)
            for i in range(gene_to_delete, genes-1):
#                 print i
                gene_pool[i] = copy.deepcopy(gene_pool[i+1])
#             if not gene_to_delete == genes - 1:
            gene_pool.pop(genes - 1)
            genes = genes-1
            if genes == 0:
                print "Gene Pool Empty !"
                break


                
## Building coevolution network
G = nx.Graph()
for g_a in gene_pool.keys():
    for g_b in gene_pool.keys():
        if not g_a == g_b: 
            if len(set(gene_pool[g_a]).intersection(gene_pool[g_b])) > 0:
                G.add_edge(g_a, g_b)
gene_pool


{0: [1, 4, 7],
 1: [5, 2],
 2: [9, 4, 5],
 3: [4],
 4: [9, 5, 6],
 5: [1, 7, 9, 2],
 6: [4, 5, 2],
 7: [8, 7],
 8: [7, 9, 2],
 9: [4, 5, 7],
 10: [9, 5],
 11: [1, 8, 7],
 12: [9, 5],
 13: [1, 9, 4, 7, 6],
 14: [1, 7],
 15: [5, 2, 9],
 16: [9, 5]}

#### Question 2


In [30]:
parser = PDBParser()
structure = parser.get_structure('pdb_file', 'pdb files/2abd.pdb')
# Iterate over all atoms in a structure
for model in structure:
    print model
    for chain in model:
        print chain
        for residue in chain:
            print residue
            for atom in residue:
                print atom
                print atom.coord
                
    break
            

<Model id=0>
<Chain id=A>
<Residue SER het=  resseq=1 icode= >
<Atom N>
[ 2.90400004  1.25399995 -4.49900007]
<Atom CA>
[ 2.11899996  2.44400001 -4.954     ]
<Atom C>
[ 3.11800003  3.58100009 -5.13800001]
<Atom O>
[ 3.46399999  3.91700006 -6.24800014]
<Atom CB>
[ 1.08800006  2.78999996 -3.83699989]
<Atom OG>
[ 1.86899996  2.5769999  -2.6559999 ]
<Atom H1>
[ 3.91100001  1.50199997 -4.40399981]
<Atom H2>
[ 2.54900002  1.00800002 -3.54900002]
<Atom H3>
[ 2.79900002  0.45899999 -5.15700006]
<Atom HA>
[ 1.64199996  2.24799991 -5.90500021]
<Atom HB2>
[ 0.75999999  3.82200003 -3.89899993]
<Atom HB3>
[ 0.229       2.13100004 -3.84899998]
<Atom HG>
[ 1.31900001  2.59100008 -1.85099995]
<Residue GLN het=  resseq=2 icode= >
<Atom N>
[ 3.53999996  4.10599995 -4.02199984]
<Atom CA>
[ 4.52899981  5.22900009 -3.96399999]
<Atom C>
[ 5.671       4.80700016 -3.00200009]
<Atom O>
[ 5.579       3.77200007 -2.36800003]
<Atom CB>
[ 3.79500008  6.48699999 -3.40300012]
<Atom CG>
[ 4.47700024  7.79300022 -3.93

<Atom N>
[ 14.00300026  20.66300011  -2.43400002]
<Atom CA>
[ 12.74600029  19.92900085  -2.13199997]
<Atom C>
[ 11.71800041  20.29400063  -3.19000006]
<Atom O>
[ 11.36600018  19.50099945  -4.03000021]
<Atom CB>
[ 12.39299965  20.44099998  -0.70999998]
<Atom CG1>
[ 12.73600006  19.41600037   0.389     ]
<Atom CG2>
[ 10.89599991  20.83099937  -0.42899999]
<Atom CD1>
[ 14.10499954  18.73999977   0.28299999]
<Atom H>
[ 14.46899986  21.12599945  -1.699     ]
<Atom HA>
[ 12.92199993  18.86599922  -2.16300011]
<Atom HB>
[ 13.00800037  21.33499908  -0.62699997]
<Atom HG12>
[ 12.70699978  19.9489994    1.32700002]
<Atom HG13>
[ 11.97399998  18.64800072   0.41999999]
<Atom HG21>
[ 10.23200035  19.99300003  -0.59600002]
<Atom HG22>
[ 10.81099987  21.12199974   0.60699999]
<Atom HG23>
[ 10.55099964  21.67300034  -1.005     ]
<Atom HD11>
[ 14.88399982  19.48600006   0.27500001]
<Atom HD12>
[ 14.21399975  18.14999962   1.18099999]
<Atom HD13>
[ 14.19999981  18.07699966  -0.57099998]
<Residue TYR het

[ 15.82999992  36.07500076  -0.89200002]
<Atom HZ3>
[ 14.41399956  36.04499817  -1.88600004]
<Residue GLY het=  resseq=51 icode= >
<Atom N>
[ 10.47999954  34.22000122  -3.91899991]
<Atom CA>
[  9.64000034  33.27500153  -4.73699999]
<Atom C>
[ 10.45600033  32.81399918  -5.91400003]
<Atom O>
[ 10.66899967  31.63800049  -6.12400007]
<Atom H>
[ 10.91899967  34.97900009  -4.37599993]
<Atom HA2>
[  9.34000015  32.41500092  -4.15799999]
<Atom HA3>
[  8.76099968  33.79000092  -5.09200001]
<Residue LYS het=  resseq=52 icode= >
<Atom N>
[ 10.89299965  33.7859993   -6.66900015]
<Atom CA>
[ 11.73600006  33.51900101  -7.89499998]
<Atom C>
[ 12.50300026  32.19200134  -7.83199978]
<Atom O>
[ 12.23200035  31.24900055  -8.5340004 ]
<Atom CB>
[ 12.76599979  34.63700104  -7.88100004]
<Atom CG>
[ 12.42300034  35.76499939  -8.87199974]
<Atom CD>
[ 12.47599983  37.08300018  -8.12899971]
<Atom CE>
[ 13.81400013  37.375       -7.4829998 ]
<Atom NZ>
[ 13.54800034  38.38999939  -6.41599989]
<Atom H>
[ 10.680999

[ 13.85299969  12.05500031  -0.12800001]
<Atom C>
[ 15.30300045  12.04500008   0.32600001]
<Atom O>
[ 15.64700031  12.63000011   1.33899999]
<Atom CB>
[ 13.45699978  10.53499985  -0.175     ]
<Atom CG1>
[ 12.28999996  10.1590004   -1.13      ]
<Atom CG2>
[ 13.21000004  10.10599995   1.28299999]
<Atom CD1>
[ 11.44200039  11.31599998  -1.50999999]
<Atom H>
[ 13.57499981  12.31499958  -2.30200005]
<Atom HA>
[ 13.20800018  12.56499958   0.59100002]
<Atom HB>
[ 14.28999996   9.93700027  -0.528     ]
<Atom HG12>
[ 12.86400032   9.91699982  -2.01799989]
<Atom HG13>
[ 11.58899975   9.34200001  -0.833     ]
<Atom HG21>
[ 14.09700012  10.3039999    1.87      ]
<Atom HG22>
[ 12.3739996   10.61900043   1.73199999]
<Atom HG23>
[ 13.05799961   9.04199982   1.29999995]
<Atom HD11>
[ 11.05200005  11.7869997   -0.62800002]
<Atom HD12>
[ 11.93200016  12.04300022  -2.10299993]
<Atom HD13>
[ 10.68000031  10.92599964  -2.14199996]
<Residue ASP het=  resseq=75 icode= >
<Atom N>
[ 16.09300041  11.36800003  -

#### Question 3


#### Question 4
